services:
  front_desk_api:
    restart: always
    container_name: front_desk_api
    build: .
    pid: "host"
    stdin_open: true   # Keep STDIN open for interactive use (-i)
    tty: true          # Allocate a TTY for terminal (-t)
    ports:
      - 42069:8080
    env_file:
      - .env
    healthcheck:
      test: curl --fail http://localhost:8080 || exit 1
      interval: 10m
      timeout: 30s
      retries: 5
      start_period: 30s
    labels:
      front-desk.name: FrontDesk API
      front-desk.url: pessimaideia.com
      front-desk.dir: /front_desk
      front-desk.logo: https://example.com/logo.png
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/apps:/src/apps
    
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    labels:
      front-desk.name: Zookeeper
      front-desk.url: 
      front-desk.dir: /front_desk
      front-desk.logo: https://example.com/logo.png

  kafka:
    image: confluentinc/cp-kafka:7.3.3
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    labels:
      front-desk.name: Kafka
      front-desk.url: 
      front-desk.dir: /front_desk
      front-desk.logo: https://example.com/logo.png
