services:
  server:
    restart: always
    container_name: front_desk_api
    build: .
    pid: "host"
    stdin_open: true   # Keep STDIN open for interactive use (-i)
    tty: true          # Allocate a TTY for terminal (-t)
    ports:
      - 42069:8080
    healthcheck:
      test: curl --fail http://localhost:8080 || exit 1
      interval: 10m
      timeout: 30s
      retries: 5
      start_period: 30s
    labels:
      front-desk.name: FrontDesk API
      front-desk.url: pessimaideia.com
      front-desk.dir: /front_desk
      front-desk.logo: https://example.com/logo.png
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/apps:/src/apps